// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANsD5nE9Fcaan6R-tIxKnKCOA2dtQzgYE',
    appId: '1:877080556597:web:d72185bcf9855a1cc46d7c',
    messagingSenderId: '877080556597',
    projectId: 'plaster-plus',
    authDomain: 'plaster-plus.firebaseapp.com',
    storageBucket: 'plaster-plus.appspot.com',
    measurementId: 'G-NQRXV4LJYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQO3Ig10MdHTaB867y8v25NaEyhqOSP8U',
    appId: '1:877080556597:android:e2a7ff5027302ea9c46d7c',
    messagingSenderId: '877080556597',
    projectId: 'plaster-plus',
    storageBucket: 'plaster-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjAV1a5cTrDafV7z8KqqEkHLL4VU9e7R4',
    appId: '1:877080556597:ios:911db0e87db56264c46d7c',
    messagingSenderId: '877080556597',
    projectId: 'plaster-plus',
    storageBucket: 'plaster-plus.appspot.com',
    iosClientId: '877080556597-4jvirkgmqhrc8cbl72rphenqon6d0oqh.apps.googleusercontent.com',
    iosBundleId: 'com.PlasterPlus.PlasterPlusapp',
  );
}
